# write a docker compose file to run the app from the current directory
version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "4200:4200"
      - "3000:3000"
    volumes:
      - .:/app-volume