previewsEnabled: false
previewsExpireAfterDays: 2
services:
  - type: web
    name: Docit
    env: docker
    dockerfilePath: ./docker/Dockerfile
    dockerContext: ./
    # healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: PORT
        value: 80
databases:
  - name: postgres-db
    plan: starter
    databaseName: docit_db_preview
    postgresMajorVersion: 15
