previewsEnabled: false
previewsExpireAfterDays: 2
services:
  - type: web
    name: monorepo-template
    env: docker
    dockerfilePath: ./docker/Dockerfile
    dockerContext: ./
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: PORT
        value: 80
      # - key: CUSTOM_DOMAIN
      #   value: 
databases:
  - name: postgres-db
    plan: starter
    databaseName: test_db
    postgresMajorVersion: 15
